name: "MLflow + DVC Trainer"
description: "Run ML training with MLflow tracking and DVC data versioning"

inputs:
  mlflow_tracking_uri:
    description: "MLflow tracking server URI"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - |
      echo "Running MLOps pipeline"
      export MLFLOW_TRACKING_URI=${{ inputs.mlflow_tracking_uri }}
      dvc pull
      dvc repro
      dvc push
